"""Add segmentations table and job segmentation_tasks field

Revision ID: 2c226f914cdd
Revises: 88ac23c61685
Create Date: 2025-04-30 04:29:44.579288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c226f914cdd'
down_revision: Union[str, None] = '88ac23c61685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('segmentation_tasks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'segmentation_tasks')
    # ### end Alembic commands ###
