"""Add segmentations table

Revision ID: 88ac23c61685
Revises: 2e7a6b5e508b
Create Date: 2025-04-30 04:19:39.421937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ac23c61685'
down_revision: Union[str, None] = '2e7a6b5e508b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segmentation_job_page', 'segmentations', ['job_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_segmentations_id'), 'segmentations', ['id'], unique=False)
    op.create_index(op.f('ix_segmentations_job_id'), 'segmentations', ['job_id'], unique=False)
    op.create_index(op.f('ix_segmentations_page_number'), 'segmentations', ['page_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segmentations_page_number'), table_name='segmentations')
    op.drop_index(op.f('ix_segmentations_job_id'), table_name='segmentations')
    op.drop_index(op.f('ix_segmentations_id'), table_name='segmentations')
    op.drop_index('ix_segmentation_job_page', table_name='segmentations')
    op.drop_table('segmentations')
    # ### end Alembic commands ###
