"""Create jobs table

Revision ID: adbd604b3391
Revises: 
Create Date: 2025-04-27 21:38:51.704946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbd604b3391'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('input_pdf_filename', sa.String(), nullable=True),
    sa.Column('input_pdf_s3_path', sa.String(), nullable=True),
    sa.Column('output_tex_s3_path', sa.String(), nullable=True),
    sa.Column('output_pdf_s3_path', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RENDERING', 'PROCESSING_VLM', 'COMPILING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_input_pdf_filename'), 'jobs', ['input_pdf_filename'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_input_pdf_filename'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
