"""Add job_page_images table

Revision ID: 2e7a6b5e508b
Revises: adbd604b3391
Create Date: 2025-04-30 04:05:02.480717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7a6b5e508b'
down_revision: Union[str, None] = 'adbd604b3391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_page_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_page_images_id'), 'job_page_images', ['id'], unique=False)
    op.create_index(op.f('ix_job_page_images_job_id'), 'job_page_images', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_page_images_job_id'), table_name='job_page_images')
    op.drop_index(op.f('ix_job_page_images_id'), table_name='job_page_images')
    op.drop_table('job_page_images')
    # ### end Alembic commands ###
